spring.application.name=module1Introduction
#notification.type = sms #can be taken from ENV as well when present at botht then ENV takes precedence
#debug=true # helps you with the logs and details of matches while creating beans